/**
 * Font Awesome Pro 5.15.4 Configuration
 * 
 * This file initializes Font Awesome Pro icons for use throughout the application.
 * We're using the library approach for better tree-shaking and performance.
 */

import { library } from '@fortawesome/fontawesome-svg-core';
import { config } from '@fortawesome/fontawesome-svg-core';

// Prevent Font Awesome from adding its CSS since we're importing it manually
config.autoAddCss = false;

// Import brand icons (free)
import {
  faDiscord,
  faGithub,
  faDocker,
  faPython,
  faReact,
  faJs,
  faNpm,
} from '@fortawesome/free-brands-svg-icons';

// Import solid icons (Free)
import {
  faServer,
  faDatabase,
  faChartLine,
  faCheckCircle,
  faExclamationTriangle,
  faTimesCircle,
  faCog,
  faUser,
  faLock,
  faUnlock,
  faSave,
  faTrash,
  faEdit,
  faPlus,
  faMinus,
  faSync,
  faDownload,
  faUpload,
  faFilm,
  faTv,
  faMusic,
  faBell,
  faBellSlash,
  faEye,
  faEyeSlash,
  faClipboard,
  faClipboardCheck,
  faShieldAlt,
  faKey,
  faNetworkWired,
  faWifi,
  faCircle,
  faMoon,
  faSun,
  faAdjust,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faExpand,
  faCompress,
  faCode,
  faTerminal,
  faBug,
  faSearch,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faCalendar,
  faClock,
  faHistory,
  faRedo,
  faUndo,
  faCloudDownloadAlt,
  faCloudUploadAlt,
  faExclamationCircle,
  faInfoCircle,
  faQuestionCircle,
  faPalette,
  faBrush,
  faKeyboard,
  faMousePointer,
  faDesktop,
  faMobile,
  faTablet,
  faLaptop,
  faHdd,
  faMemory,
  faMicrochip,
  faThermometerHalf,
  faTachometerAlt,
  faChartBar,
  faChartPie,
  faChartArea,
  faRocket,
  faSpinner,
  faCircleNotch,
  faUserCheck,
  faArrowCircleUp,
  faCogs,
  faTools,
  faWrench,
  faExchangeAlt,
  faSignal,
  faHome,
  faFileAlt,
  faSearchPlus,
  faSignOutAlt,
  faBars,
  faTimes,
  faCommentAlt,
  faFileCode,
  faChevronDown,
  faCheck,
  faUserShield,
} from '@fortawesome/free-solid-svg-icons';

// Import regular icons (Free)
import {
  faBell as farBell,
  faCheckCircle as farCheckCircle,
  faTimesCircle as farTimesCircle,
  faQuestionCircle as farQuestionCircle,
  faLightbulb as farLightbulb,
  faFile as farFile,
  faFileAlt as farFileAlt,
  faFileCode as farFileCode,
  faFolder as farFolder,
  faFolderOpen as farFolderOpen,
  faStar as farStar,
  faHeart as farHeart,
  faComment as farComment,
  faComments as farComments,
  faEnvelope as farEnvelope,
  faCalendarAlt as farCalendarAlt,
  faClock as farClock,
  faUser as farUser,
  faUserCircle as farUserCircle,
  faSmile as farSmile,
  faFrown as farFrown,
  faMeh as farMeh,
} from '@fortawesome/free-regular-svg-icons';

// Light icons removed (Pro only) - using solid equivalents

// Duotone icons removed (Pro only) - using solid equivalents

// Add all icons to the library
library.add(
  // Brands
  faDiscord,
  faGithub,
  faDocker,
  faPython,
  faReact,
  faJs,
  faNpm,
  
  // Solid
  faServer,
  faDatabase,
  faChartLine,
  faCheckCircle,
  faExclamationTriangle,
  faTimesCircle,
  faCog,
  faUser,
  faLock,
  faUnlock,
  faSave,
  faTrash,
  faEdit,
  faPlus,
  faMinus,
  faSync,
  faDownload,
  faUpload,
  faFilm,
  faTv,
  faMusic,
  faBell,
  faBellSlash,
  faEye,
  faEyeSlash,
  faClipboard,
  faClipboardCheck,
  faShieldAlt,
  faKey,
  faWebhook,
  faNetworkWired,
  faWifi,
  faWifiSlash,
  faCircle,
  faMoon,
  faSun,
  faAdjust,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faExpand,
  faCompress,
  faCode,
  faTerminal,
  faBug,
  faSearch,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faCalendar,
  faClock,
  faHistory,
  faRedo,
  faUndo,
  faCloudDownloadAlt,
  faCloudUploadAlt,
  faExclamationCircle,
  faInfoCircle,
  faQuestionCircle,
  faPalette,
  faBrush,
  faKeyboard,
  faMousePointer,
  faDesktop,
  faMobile,
  faTablet,
  faLaptop,
  faHdd,
  faMemory,
  faMicrochip,
  faThermometerHalf,
  faTachometerAlt,
  faChartBar,
  faChartPie,
  faChartArea,
  faRocket,
  faSpinner,
  faCircleNotch,
  
  // Regular
  farBell,
  farCheckCircle,
  farTimesCircle,
  farQuestionCircle,
  farLightbulb,
  farFile,
  farFileAlt,
  farFileCode,
  farFolder,
  farFolderOpen,
  farStar,
  farHeart,
  farComment,
  farComments,
  farEnvelope,
  farCalendarAlt,
  farClock,
  farUser,
  farUserCircle,
  farSmile,
  farFrown,
  farMeh,
  
  // Additional solid icons as fallbacks
  faUserCheck,
  faArrowCircleUp,
  faCogs,
  faTools,
  faWrench,
  faExchangeAlt,
  faSignal,
  faHome,
  faFileAlt,
  faSearchPlus,
  faSignOutAlt,
  faBars,
  faTimes,
  faCommentAlt,
  faFileCode,
  faChevronDown,
  faCheck,
  faUserShield
);

// Export the FontAwesomeIcon component for use in React components
export { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

// Export icon name mappings for easy reference
export const iconNames = {
  // Service brands
  discord: ['fab', 'discord'],
  github: ['fab', 'github'],
  docker: ['fab', 'docker'],
  
  // Media types  
  movie: ['fas', 'film'],
  tv: ['fas', 'tv'],
  music: ['fas', 'music'],
  
  // Status icons
  online: ['fas', 'circle'],
  offline: ['fas', 'circle'],
  connecting: ['fas', 'spinner'],
  
  // Theme icons
  dark: ['fas', 'moon'],
  light: ['fas', 'sun'],
  auto: ['fas', 'adjust'],
  
  // Common actions
  save: ['fas', 'save'],
  delete: ['fas', 'trash'],
  edit: ['fas', 'edit'],
  add: ['fas', 'plus'],
  remove: ['fas', 'minus'],
  refresh: ['fas', 'sync'],
  download: ['fas', 'download'],
  upload: ['fas', 'upload'],
  
  // Security
  locked: ['fas', 'lock'],
  unlocked: ['fas', 'unlock'],
  shield: ['fas', 'shield-alt'],
  userShield: ['fas', 'user-shield'],
  
  // System
  server: ['fas', 'server'],
  database: ['fas', 'database'],
  network: ['fas', 'network-wired'],
  webhook: ['fas', 'code-branch'],
  
  // Charts
  analytics: ['fas', 'chart-line'],
  chartLine: ['fas', 'chart-line'],
  monitoring: ['fas', 'heartbeat'],
};

// Helper function to get icon by name
export const getIcon = (name) => {
  return iconNames[name] || ['fas', 'question-circle'];
};